spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: password

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    contexts: development
    drop-first: false

  jpa:
    hibernate:
      ddl-auto: none  # Let Liquibase handle schema

server:
  port: 8989

logging:
  level:
    com.pricetracker: DEBUG
    liquibase: INFO